# .github/workflows/c-cpp.yml: workflow file for github action CI
# Copyright (C) 2023 Guoxin "7Ji" Pu <pugokushin@gmail.com>

# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.


name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Static build for x86_64
      run: make fresh STATIC=1
    - name: Rename for x86_64
      run: mv YAopenvfD YAopenvfD-x86_64
    - name: Install cross toolchain for aarch64
      run: |
        sudo dpkg --add-architecture arm64
        CODENAME=$(lsb_release -c -s)
        sudo bash -c "echo -e '\
          deb [arch=arm64] http://ports.ubuntu.com/ $CODENAME main restricted \n\
          deb [arch=arm64] http://ports.ubuntu.com/ $CODENAME-updates main restricted \n\
          deb [arch=arm64] http://ports.ubuntu.com/ $CODENAME universe \n\
          deb [arch=arm64] http://ports.ubuntu.com/ $CODENAME-updates universe \n\
          deb [arch=arm64] http://ports.ubuntu.com/ $CODENAME multiverse \n\
          deb [arch=arm64] http://ports.ubuntu.com/ $CODENAME-updates multiverse \n\
          deb [arch=arm64] http://ports.ubuntu.com/ $CODENAME-backports main restricted universe multiverse \n' > /etc/apt/sources.list.d/arm64-cross.list"
        sudo sed -i 's/deb http/deb [arch=amd64] http/g' /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install \
          gcc-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu \
          linux-libc-dev:arm64
    - name: Static build for aarch64
      run: make fresh CC=aarch64-linux-gnu-gcc STRIP=aarch64-linux-gnu-strip STATIC=1
    - name: Rename for aarch64
      run: mv YAopenvfD YAopenvfD-aarch64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: static-build
        path: YAopenvfD-*
        if-no-files-found: error
        retention-days: 0
